---
- name: Server Provisioning
  hosts: all
  remote_user: vagrant
  become: true
  tasks:
    - name: update repository
      replace:
        path: /etc/apt/sources.list
        regexp: "{{ item }}"
        replace: 'mirror.kakao.com'
      with_items:
        - 'kr.archive.ubuntu.com'
        - 'archive.ubuntu.com'
        - 'security.ubuntu.com'
    
    - name: apt-get update
      apt:
        update-cache: yes
      changed_when: 0
      ignore_errors: yes
    
    - name: Upgrading all packages (Ubuntu/Debian)
      apt:
        upgrade: dist
        force: yes
    
    - name: Install prerequisites
      apt:
        name:
          - curl
          - vim
          - htop
          - build-essential
          - python3-pip
        force: yes
        state: present
    
    - name: Add Docker apt key.
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        state: present
      register: docker_apt_key_added
    
    - name: Add Docker repository.
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
     
    - name: update apt cache
      apt:
        update-cache: yes
      ignore_errors: yes
    
    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        force: yes
        state: present
    - name: Restart docker
      service:
        name: docker
        state: restarted
      ignore_errors: yes
    
    - name: add group
      user:
        name: vagrant
        groups: docker
        append: yes
    
    - name: pip docker
      pip:
        name:
          - docker
          - docker-compose
    
    - name: create docker-daemon.json
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "userland-proxy": false
          }
    
    - name: optimize
      command: "{{ item }}"
      with_items:
        - apt-get clean
        - rm -rf /var/lib/apt/lists/*
        - dd if=/dev/zero of=/EMPTY bs=1M
        - rm -f /EMPTY
        - cat /dev/null > ~/.bash_history
      ignore_errors: yes
